# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Doma < Formula
  desc "Put your directories on the cutting board"
  homepage "https://github.com/hahwul/doma"
  url "https://github.com/hahwul/doma/archive/refs/tags/v0.1.1.tar.gz"
  sha256 "0b329acbb737bcbdbcbc593e34811351d44e918ac30ba6c8a6ed26479c8f3a70"
  license "MIT"

  depends_on "crystal"
  depends_on "sqlite"

  def install
    system "shards install"
    system "shards build --release --no-debug --production"
    bin.install "bin/doma"
  end

  test do
    system "#{bin}/doma", "version"
  end
end
