# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Doma < Formula
  desc "Put your directories on the cutting board"
  homepage "https://github.com/hahwul/doma"
  url "https://github.com/hahwul/doma/archive/refs/tags/v0.2.0.tar.gz"
  sha256 "158220fbfe005da8800e53cbfdb1d0f3815b151950692fcf1d3c44f10cc1f2e0"
  license "MIT"

  depends_on "crystal"
  depends_on "sqlite"

  def install
    system "shards install"
    system "shards build --release --no-debug --production"
    bin.install "bin/doma"
  end

  test do
    system "#{bin}/doma", "version"
  end
end
