# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Doma < Formula
  desc "Put your directories on the cutting board"
  homepage "https://github.com/hahwul/doma"
  url "https://github.com/hahwul/doma/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "de595c22912b351ce951d0f5fbd783b0cab500984e5d5c474c21bfc181ad62a4"
  license "MIT"

  depends_on "crystal"
  depends_on "sqlite"

  def install
    system "shards install"
    system "shards build --release --no-debug --production"
    bin.install "bin/doma"
  end

  test do
    system "#{bin}/doma", "version"
  end
end
